### ISSUE TITLE
Amazon Price Lookup Service

### ISSUE THREAD

**Issue by honerlaw** [honerlaw/alert-me#2]
Currently, it seems the price service only runs at 8 am once and it should run at 8am daily. (At least based on the logs it attempted to run on 11/25 at 8am and has not tried to run since then).

Below is the exception that occurred (and potentially broke the service, so that may need to be fixed to handle exceptions better).

```
[2016-11-25 08:00:00] [WARNING] [io.honerlaw.alertme.data.EntityManager] Failed to execute query because data is supplied but empty
[2016-11-25 08:00:00] [WARNING] [io.honerlaw.alertme.data.EntityManager] Failed to execute query because data is supplied but empty
[2016-11-25 08:00:00] [SEVERE] [io.vertx.core.impl.ContextImpl] Unhandled exception
java.lang.IllegalStateException: Illegal type in JsonObject: class java.util.HashSet
        at io.vertx.core.json.Json.checkAndCopy(Json.java:125)
        at io.vertx.core.json.JsonArray.add(JsonArray.java:432)
        at io.honerlaw.alertme.data.QueryUtil.asJsonArray(QueryUtil.java:36)
        at io.honerlaw.alertme.lookup.service.PriceLookupService.lambda$start$2(PriceLookupService.java:48)
        at io.honerlaw.alertme.lookup.PriceLookupScheduler.lambda$null$4(PriceLookupScheduler.java:100)
        at io.honerlaw.alertme.lookup.PriceLookupScheduler.lookup(PriceLookupScheduler.java:62)
        at io.honerlaw.alertme.lookup.PriceLookupScheduler.lambda$null$5(PriceLookupScheduler.java:99)
        at io.honerlaw.alertme.data.EntityManager.transform(EntityManager.java:169)
        at io.honerlaw.alertme.data.EntityManager.lambda$null$2(EntityManager.java:52)
        at io.honerlaw.alertme.data.EntityManager.executeQuery(EntityManager.java:133)
        at io.honerlaw.alertme.data.EntityManager.lambda$query$3(EntityManager.java:51)
        at io.honerlaw.alertme.data.EntityManager.lambda$connection$6(EntityManager.java:85)
        at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:158)
        at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
        at io.vertx.ext.jdbc.impl.JDBCClientImpl.lambda$null$0(JDBCClientImpl.java:137)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:359)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:393)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by honerlaw** [comment]
Fix included converting a HashSet into an ArrayList when putting the data into a JsonObject.
